#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: agissing <agissing@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/10 14:00:52 by agissing          #+#    #+#              #
#    Updated: 2019/04/11 14:42:32 by agissing         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

################################################################################
#####                              FILES VARS                              #####
################################################################################

#main dirs
MD5_DIR       = md5
SHA256_DIR    = sha256
SHA512_DIR    = sha512
WHIRLPOOL_DIR = whirlpool

#includes
MD5_INC       = $(MD5_DIR)
SHA256_INC    = $(SHA256_DIR)
SHA512_INC    = $(SHA512_DIR)
WHIRLPOOL_INC = $(WHIRLPOOL_DIR)

#global include
INCLUDES = includes

#includes
#{{AUTO-SRC}path=includes;file=*.h;name=SRC_INCLUDES}

#{END}

#ssl
#{{AUTO-SRC}path=ssl;file=*.c;name=SRC_WHIRLPOOL}

#{END}

#md5
#{{AUTO-SRC}path=md5;file=*.c;name=SRC_MD5}

#{END}

#sha256
#{{AUTO-SRC}path=sha256;file=*.c;name=SRC_SHA256}

#{END}

#sha512
#{{AUTO-SRC}path=sha512;file=*.c;name=SRC_SHA512}

#{END}

#whirlpool
#{{AUTO-SRC}path=whirlpool;file=*.c;name=SRC_WHIRLPOOL}

#{END}
